version: 3

tasks:
  dev:
    desc: Run the frontend in development mode
    env:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    cmds:
      - npm run dev

  prettify:
    desc: Prettify all files
    cmds:
      - npm run prettier:write

  lintall:
    desc: Lint all files
    cmds:
      - npm run lint
      - npm run prettier:check

  build:
    desc: Build the frontend
    env:
      NEXT_PUBLIC_API_URL: /api
    cmds:
      - npm install
      - npm run build
      - npm run export

  all:
    desc: Run all tasks
    cmds:
      - task prettify
      - task lintall
      - task build
