version: '3'

dotenv: ['.vadikk.com.env']

includes:
  backend:
    taskfile: ./backend/taskfile.yaml
    dir: ./backend

  firmware:
    taskfile: ./firmware/taskfile.yaml
    dir: ./firmware

  frontend:
    taskfile: ./frontend/taskfile.yaml
    dir: ./frontend

  infra:
    taskfile: ./infra/taskfile.yaml
    dir: ./infra

tasks:
  'image:build':
    desc: Build the docker image
    env:
      BUILDKIT_PROGRESS: plain
    cmds:
      - echo "Building {{.IMG_NAME}}:latest"
      - docker build -t {{.IMG_NAME}}:latest -f Dockerfile .

  'image:run':
    desc: Run the docker image
    env:
      IR_SHARED_SECRET: "{{.IR_SHARED_SECRET}}"
      IR_LISTEN_PORT: "{{.IR_LISTEN_PORT}}"
    cmds:
      - "echo Running {{.IMG_NAME}}:latest"
      - "echo web: http://localhost:8000"
      - "echo udp: port $IR_LISTEN_PORT"
      - "docker run --rm  -p 8000:8000 -p $IR_LISTEN_PORT:12000/udp --env IR_SHARED_SECRET=$IR_SHARED_SECRET {{.IMG_NAME}}:latest"

  'image:console':
    desc: Console into the docker image
    cmds:
      - docker run -it --rm -p 8000:8000 {{.IMG_NAME}}:latest sh

  build:
    desc: Build the app
    cmds:
      - task: frontend:build
      - task: image:build

  deploy:
    desc: Deploy the app
    cmds:
      - task: infra:deploy

  lintall:
    desc: Lint the app
    cmds:
      - task: frontend:lintall
      - task: backend:lintall

  prettify:
    desc: Prettify the app
    cmds:
      - task: frontend:prettify
      - task: backend:prettify

  all:
    desc: Build and deploy the app
    cmds:
      - task: prettify # temporary here
      - task: lintall
      - task: build
      - task: deploy