version: 3

tasks:
  server:
    desc: Run the project
    cmds:
      - go run cmd/server/server.go

  fmt:
    desc: Run the formatter
    cmds:
      - gofmt -l .

  lintall:
    desc: Run all linters
    cmds:
      - task: fmt

  prettify:
    desc: Run the formatter
    cmds:
      - gofmt -w .