version: '3'

services:
  app:
    image: ${IMG_NAME}:latest
    restart: always
    environment:
      IR_SHARED_SECRET: ${IR_SHARED_SECRET}
      BOT_API: ${BOT_API}
      BOT_AUTHORIZED_USERS: ${BOT_AUTHORIZED_USERS}
    ports:
      - "${IR_LISTEN_PORT}:12000/udp"
